package gui_giaodich;

import java.util.ArrayList;
import java.util.List;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import dao.CT_PhieuThue_DAO;
import dao.Dia_DAO;
import dao.KhachHang_DAO;
import dao.PhieuThue_DAO;
import dao.TaiKhoan_DAO;
import dao.TieuDe_DAO;
import database.Database;
import entities.ChiTietPhieuThue;
import entities.Dia;
import entities.KhachHang;
import entities.PhieuThue;
import entities.TaiKhoan;
import entities.TieuDe;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class ChiTietPhieuThueDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public ChiTietPhieuThueDialog(java.awt.Frame parent, boolean modal,String maPT) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
		qlkh = new KhachHang_DAO();
		qlpt = new PhieuThue_DAO();
		qltk = new TaiKhoan_DAO();
		ql_ctpt = new CT_PhieuThue_DAO();
		qltd = new TieuDe_DAO();
		qldia = new Dia_DAO();

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
        txtMaPT = new javax.swing.JTextField();
        txtMaPT.setFont(new Font("Tahoma", Font.PLAIN, 20));
        txtKhachHang = new javax.swing.JTextField();
        txtKhachHang.setFont(new Font("Tahoma", Font.PLAIN, 20));
        txtNguoiLap = new javax.swing.JTextField();
        txtNguoiLap.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 20));
        txtNgayLap = new javax.swing.JTextField();
        txtNgayLap.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 20));
        txtTongTien = new javax.swing.JTextField();
        txtTongTien.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 20));

		setTitle("Chi tiết phiếu thuê");
		setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã PT:");

        jLabel2.setText("Khách hàng:");

        txtMaPT.setEditable(false);

        txtKhachHang.setEditable(false);

        txtNguoiLap.setEditable(false);

        jLabel3.setText("Ngày lập:");

        jLabel4.setText("Người lập:");

        txtNgayLap.setEditable(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setRowHeight(40);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Tên đĩa", "Hạn trả", "Thành tiền" }) {
			boolean[] canEdit = new boolean[] { false, false ,false};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});

        jScrollPane1.setViewportView(jTable1);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Chi tiết phiếu thuê:");

        txtTongTien.setEditable(false);

        jLabel6.setText("Tổng tiền:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 232, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(txtTongTien, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)))
        					.addGap(206, 523, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(txtMaPT, Alignment.LEADING)
        						.addComponent(txtKhachHang, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
        							.addGap(10)
        							.addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addGap(21)
        							.addComponent(txtNguoiLap, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addComponent(txtMaPT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(txtKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel3))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(txtNguoiLap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(18)
        			.addComponent(jLabel5)
        			.addGap(15)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtTongTien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setData(String maPT){
    	PhieuThue pt = qlpt.chiTietPhieuThue(maPT);
    	TaiKhoan tk = qltk.chiTietTaiKhoan(pt.getNhanVien().getTenTK());
    	KhachHang kh = qlkh.chiTietKhachHang(pt.getKhachHang().getMaKH());
    	txtMaPT.setText(pt.getMaPT());
    	txtNgayLap.setText(pt.getNgayThue());
    	txtKhachHang.setText(kh.getTenKH());
    	txtNguoiLap.setText(tk.getHoTen());
    	txtTongTien.setText(pt.getTongTien()+"");
    	DocDuLieuDatabaseVaoTable(maPT);
    }
    
    public void DocDuLieuDatabaseVaoTable(String maPT) {
		List<ChiTietPhieuThue> list = new ArrayList<ChiTietPhieuThue>();
		ql_ctpt = new CT_PhieuThue_DAO();
		list = ql_ctpt.getCTPT_TheoPT(maPT);
		DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
		for (ChiTietPhieuThue ctpt : list) {
			Dia d = qldia.chiTietDia(ctpt.getDia().getMaDia());
			TieuDe td = qltd.chiTietTieuDe(d.getTieuDe().getMaTD());
			dm.addRow(new Object[] {td.getTenTD(),ctpt.getHanTra(),ctpt.getThanhTien()});
		}
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtNguoiLap;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtNgayLap;
    
    private static String maPT;
    
    private  KhachHang_DAO qlkh;
    private  PhieuThue_DAO qlpt;
    private  TaiKhoan_DAO qltk;
    private  CT_PhieuThue_DAO ql_ctpt;
    private  TieuDe_DAO qltd;
    private  Dia_DAO qldia;
    // End of variables declaration//GEN-END:variables
}
