/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_giaodich;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import dao.CT_PhieuDat_DAO;
import dao.CT_PhieuThue_DAO;
import dao.Dia_DAO;
import dao.KhachHang_DAO;
import dao.PhieuDat_DAO;
import dao.PhieuThue_DAO;
import dao.TheLoai_DAO;
import dao.TieuDe_DAO;
import database.Database;
import entities.ChiTietPhieuDat;
import entities.ChiTietPhieuThue;
import entities.Dia;
import entities.KhachHang;
import entities.PhieuDat;
import entities.PhieuThue;
import entities.TheLoai;
import entities.TieuDe;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Dimension;

/**
 *
 * @author nmrhu
 */
public class TraCuu_Dia_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TraCuu_KhachHang_Gui
	 */
	public TraCuu_Dia_Gui() {
		initComponents();
		DocDuLieuDatabaseVaoTable("");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qltd = new TieuDe_DAO();
		qldia = new Dia_DAO();
		qltl = new TheLoai_DAO();
		ql_ctpt = new CT_PhieuThue_DAO();
		ql_ctpd = new CT_PhieuDat_DAO();
		qlpt = new PhieuThue_DAO();
		qlpd = new PhieuDat_DAO();
		qlkh = new KhachHang_DAO();

		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableDia = new javax.swing.JTable();
		btnTim = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 28));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 28));
		txtTim = new javax.swing.JTextField();
		txtTim.setFont(new Font("Tahoma", Font.PLAIN, 20));

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new Dimension(1500, 700));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTableDia.setRowHeight(40);
		jTableDia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTableDia.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã đĩa", "Tên đĩa", "Thể loại", "Tình trạng", "Khách hàng" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTableDia.setModel(dm);
		jScrollPane1.setViewportView(jTableDia);
		jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		btnTim.setBackground(new java.awt.Color(0, 153, 255));
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm kiếm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String txt = txtTim.getText().toString();
				DocDuLieuDatabaseVaoTable(txt);
			}
		});

		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("/ Tra cứu");

		jLabel1.setForeground(new java.awt.Color(51, 153, 255));
		jLabel1.setText("Giao dịch");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel2)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}

	
	public void DocDuLieuDatabaseVaoTable(String txt) {
		dm = (DefaultTableModel) jTableDia.getModel();
		dm.setRowCount(0);
		List<Dia> list = new ArrayList<Dia>();
		qldia = new Dia_DAO();

		if (txt.equals(""))
			list = qldia.dsDia();
		else
			list = qldia.tim_Dia(txt);

		if (list.size() == 0) {
			JOptionPane.showMessageDialog(null, "Không tìm thấy");
		}

		for (Dia d : list) {
			TieuDe td = qltd.chiTietTieuDe(d.getTieuDe().getMaTD());
			TheLoai tl = qltl.chiTietTheLoai(d.getTheLoai().getMaTL());
			String tinhTrang, huHong;
			KhachHang kh = null;
			if (d.getTinhTrang() == 0) {
				tinhTrang = "Có sẵn";
			} else if (d.getTinhTrang() == 1) {
				tinhTrang = "Cho thuê";
				ChiTietPhieuThue ctpt = ql_ctpt.getPhieuThueGanNhat_TheoDia(d.getMaDia());
				PhieuThue pt = qlpt.chiTietPhieuThue(ctpt.getPhieuThue().getMaPT());
				kh = qlkh.chiTietKhachHang(pt.getKhachHang().getMaKH());
			} else {
				tinhTrang = "Đặt hàng";
				ChiTietPhieuDat ctpd = ql_ctpd.getPhieuDatGanNhat_TheoMaDia(d.getMaDia());
				PhieuDat pd = qlpd.chiTietPhieuDat(ctpd.getPhieuDat().getMaDH());
				kh = qlkh.chiTietKhachHang(pd.getKhachHang().getMaKH());
			}
			if (kh == null)
				dm.addRow(new Object[] { d.getMaDia(), td.getTenTD(), tl.getTenTL(), tinhTrang, "" });
			else
				dm.addRow(new Object[] { d.getMaDia(), td.getTenTD(), tl.getTenTL(), tinhTrang, kh.getTenKH() });
		}

	}

	private javax.swing.JButton btnTim;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableDia;
	private javax.swing.JTextField txtTim;
	private javax.swing.table.DefaultTableModel dm;

	private Dia_DAO qldia;
	private TheLoai_DAO qltl;
	private TieuDe_DAO qltd;
	private CT_PhieuThue_DAO ql_ctpt;
	private PhieuThue_DAO qlpt;
	private CT_PhieuDat_DAO ql_ctpd;
	private PhieuDat_DAO qlpd;
	private KhachHang_DAO qlkh;
	// End of variables declaration//GEN-END:variables
}
