/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_danhMuc;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import dao.KhachHang_DAO;
import dao.TaiKhoan_DAO;
import database.Database;
import entities.KhachHang;
import entities.TaiKhoan;
import gui_main.Main;
import java.awt.Font;

/**
 *
 * @author nmrhu
 */
public class KhachHang_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form TaiKhoan_DL
	 */
	public KhachHang_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		getID();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkh = new KhachHang_DAO();

		btnLuu = new javax.swing.JButton();
		btnXoaTrang = new javax.swing.JButton();
		txtMaKH = new javax.swing.JTextField();
		txtMaKH.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaKH.setEditable(false);
		txtHoTen = new javax.swing.JTextField();
		txtHoTen.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSDT = new javax.swing.JTextField();
		txtSDT.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtDiaChi = new javax.swing.JTextField();
		txtDiaChi.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 20));

		setResizable(false);
		setBackground(new java.awt.Color(255, 255, 255));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (quyen == 1)
					ThemKhachHang();
				if (quyen == 2)
					CapNhatKhachHang();
			}
		});

		txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});

		btnXoaTrang.setBackground(new java.awt.Color(255, 0, 0));
		btnXoaTrang.setForeground(new java.awt.Color(255, 255, 255));
		btnXoaTrang.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnXoaTrang.setText("Đóng");
		btnXoaTrang.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

		jLabel1.setText("MãKH:");

		jLabel2.setText("Họ tên:");

		jLabel3.setText("SĐT:");

		jLabel4.setText("Địa chỉ:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtMaKH).addComponent(txtHoTen).addComponent(txtSDT)
								.addComponent(txtDiaChi)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 153,
												Short.MAX_VALUE)))
						.addGap(23, 23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnLuu).addComponent(btnXoaTrang))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void getID() {
		int id = qlkh.getMaKH();
		String maKH = "";
		if (id == 0) {
			maKH = "KH00001";
		} else if (id < 10)
			maKH = "KH0000" + id;
		else if (id < 100)
			maKH = "KH000" + id;
		else if (id < 1000)
			maKH = "KH00" + id;
		else if (id < 10000)
			maKH = "KH0" + id;
		else
			maKH = "KH" + id;

		txtMaKH.setText(maKH);
	}

	public void setData(KhachHang kh) {
		txtMaKH.setText(kh.getMaKH());
		txtHoTen.setText(kh.getTenKH());
		txtSDT.setText(kh.getSdt());
		txtDiaChi.setText(kh.getDiaChi());
	}

	public void clear() {
		getID();
		txtHoTen.setText("");
		txtSDT.setText("");
		txtDiaChi.setText("");
	}

	public void lienLacKhachHang(KhachHang kh) {
		txtMaKH.setText(kh.getMaKH());
		txtHoTen.setText(kh.getTenKH());
		txtSDT.setText(kh.getSdt());
		txtDiaChi.setText(kh.getDiaChi());
		txtHoTen.setEditable(false);
		txtSDT.setEditable(false);
		txtDiaChi.setEditable(false);
		btnLuu.setEnabled(false);
	}

	public void ThemKhachHang() {
		if (kiemTraNhap()) {
			try {
				qlkh.themKhachHang(getKhachHang());
				main.khachHang_pn.DocDuLieuDatabaseVaoTable("");
				main.phieuThue_pn.LapPhieu_pn.DocDuLieuDatabaseVaoList("");
				main.datHang_pn.lapDatHang_pn.DocDuLieuDatabaseVaoList("");
				JOptionPane.showMessageDialog(null, "Thêm thành công");
				clear();
			} catch (HeadlessException e) {
				JOptionPane.showMessageDialog(null, "Thêm không thành công");
			}
		}
	}

	public void CapNhatKhachHang() {
		try {
			qlkh.capNhatKhachHang(getKhachHang());
			JOptionPane.showMessageDialog(null, "Cập nhật thành công");
			main.khachHang_pn.DocDuLieuDatabaseVaoTable("");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
		}
	}

	public boolean kiemTraNhap() {
		String hoTen = txtHoTen.getText();
		String diaChi = txtDiaChi.getText();
		String sdt = txtSDT.getText();

		if (hoTen.equals("") || diaChi.equals("") || sdt.equals("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
			return false;
		}
		if (sdt.length() != 10) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại hợp lệ với 10 số");
			txtSDT.requestFocus();
			return false;
		}
		return true;
	}

	public KhachHang getKhachHang() {
		String maKH = txtMaKH.getText();
		String hoTen = txtHoTen.getText();
		String sdt = txtSDT.getText();
		String diaChi = txtDiaChi.getText();
		KhachHang kh = new KhachHang(maKH, hoTen, sdt, diaChi);
		return kh;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLuu;
	private javax.swing.JButton btnXoaTrang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField txtDiaChi;
	private javax.swing.JTextField txtHoTen;
	private javax.swing.JTextField txtMaKH;
	private javax.swing.JTextField txtSDT;

	private Main main;
	public static int quyen;
	private KhachHang_DAO qlkh;

	// End of variables declaration//GEN-END:variables
}
