package gui_danhMuc;

import java.awt.HeadlessException;

import javax.swing.JOptionPane;

import dao.TieuDe_DAO;
import database.Database;
import entities.TaiKhoan;
import gui_main.Main;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class TenDia_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public TenDia_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		getID();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qltd = new TieuDe_DAO();
		
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaTD = new javax.swing.JTextField();
		txtMaTD.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtTenTD = new javax.swing.JTextField();
		txtTenTD.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnLuu = new javax.swing.JButton();
		btnDong = new javax.swing.JButton();

		setResizable(false);
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Mã tiêu đề");

		jLabel2.setText("Tên tiêu đề");

		txtMaTD.setEditable(false);

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String tenTD = txtTenTD.getText().toString();
				if (tenTD.equals("")) {
					JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
				} else {
					try {
						qltd.themTieuDe(tenTD);
						JOptionPane.showMessageDialog(null, "Thêm thành công");
						main.tenDia_pn.DocDuLieuDatabaseVaoTable("");
						getID();
						txtTenTD.setText("");
					} catch (HeadlessException e) {
						JOptionPane.showMessageDialog(null, "Thêm không thành công");
					}
				}
			}
		});

		btnDong.setBackground(new java.awt.Color(255, 0, 0));
		btnDong.setForeground(new java.awt.Color(255, 255, 255));
		btnDong.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnDong.setText("Đóng");
		btnDong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
        		dispose();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtMaTD, javax.swing.GroupLayout.DEFAULT_SIZE, 333,
												Short.MAX_VALUE)
										.addComponent(txtTenTD))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
												Short.MAX_VALUE)
										.addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(18, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(txtMaTD, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtTenTD, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnLuu).addComponent(btnDong))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}
	
	public void getID() {
		int id = qltd.getMaTieuDe();
		String maTD = null;
		if (id == 0) {
			maTD = "TD00001";
		} else if (id < 10)
			maTD = "TD0000" + id;
		else if (id < 100)
			maTD = "TD000" + id;
		else if (id < 1000)
			maTD = "TD00" + id;
		else if (id < 10000)
			maTD = "TD0" + id;
		else
			maTD = "TD" + id;

		txtMaTD.setText(maTD);
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDong;
	private javax.swing.JButton btnLuu;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtMaTD;
	private javax.swing.JTextField txtTenTD;

	private Main main;
	private TieuDe_DAO qltd;
	// End of variables declaration//GEN-END:variables
}
