/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_heThong;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import database.Database;
import entities.ChiTietPhieuThue;
import entities.Dia;
import entities.KhachHang;
import entities.PhieuThue;
import entities.PhieuTra;
import entities.TaiKhoan;
import entities.TieuDe;
import gui_giaodich.GhiNhanTra_Gui;
import gui_giaodich.PhieuTra_Gui;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import com.toedter.calendar.JDateChooser;

import dao.CT_PhieuThue_DAO;
import dao.Dia_DAO;
import dao.KhachHang_DAO;
import dao.PhieuThue_DAO;
import dao.PhieuTra_DAO;
import dao.TaiKhoan_DAO;
import dao.TieuDe_DAO;

import java.awt.Font;
import java.awt.Dimension;

/**
 *
 * @author nmrhu
 */
public class PhieuTra_DS_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TraCuu_KhachHang_Gui
	 */
	public PhieuTra_DS_Gui() {
		initComponents();

		DocDuLieuDatabaseVaoTable("",0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlptr = new PhieuTra_DAO();
		qlpt = new PhieuThue_DAO();
		qltd = new TieuDe_DAO();
		qldia = new Dia_DAO();
		ql_ctpt = new CT_PhieuThue_DAO();
		qltk = new TaiKhoan_DAO();

		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableDia = new javax.swing.JTable();
		btnTim = new javax.swing.JButton();
		txtTim = new javax.swing.JTextField();
		txtTim.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnTim1 = new javax.swing.JButton();
		btnLapPhieuThue = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new Dimension(1274, 608));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTableDia.setRowHeight(40);
		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã PTr", "Mã đĩa", "Tên đĩa", "Hạn Trả", "Ngày Trả", "Quá hạn", "Hư hỏng", "Người lập" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false, false, false};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTableDia.setModel(dm);
		jTableDia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTableDia.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
		jScrollPane1.setViewportView(jTableDia);

		jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		btnTim.setBackground(new java.awt.Color(0, 153, 255));
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm kiếm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String txt = txtTim.getText().toString();
				DocDuLieuDatabaseVaoTable(txt, 0);
			}
		});

		btnTim1.setBackground(new java.awt.Color(0, 153, 255));
		btnTim1.setForeground(new java.awt.Color(255, 255, 255));
		btnTim1.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\DoAnQuanLyChoThueBangDia\\XayDungPhanMem\\img\\filter_30px.png")); // NOI18N
		btnTim1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DocDuLieuDatabaseVaoTable("", 1);
				txtTim.setText("");
			}
		});

		btnLapPhieuThue.setBackground(new java.awt.Color(51, 153, 255));
		btnLapPhieuThue.setForeground(new java.awt.Color(255, 255, 255));
		btnLapPhieuThue.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\add_property_30px.png")); // NOI18N
		btnLapPhieuThue.setText("Ghi nhận trả");
		btnLapPhieuThue.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pt.lapPhieuTra(tk);
			}
		});

		dateChooser = new JDateChooser();
		dateChooser.setDate(new Date());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnTim1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
							.addComponent(btnLapPhieuThue, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
							.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(btnTim, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(btnLapPhieuThue, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(dateChooser, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnTim1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addGap(16)))
					.addGap(0)
					.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
					.addContainerGap())
		);
		this.setLayout(layout);
	}

	public void DocDuLieuDatabaseVaoTable(String txt, int tim) {
		dm = (DefaultTableModel) jTableDia.getModel();
		dm.setRowCount(0);

		List<PhieuTra> list = new ArrayList<PhieuTra>();
		qlptr = new PhieuTra_DAO();

		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		if (tim == 1) {
			
			String date = sdf.format(dateChooser.getDate());
			list = qlptr.timPhieuTra_Ngay(date);

		} else {
			dateChooser.setDate(new Date());
			String date1 = sdf.format(dateChooser.getDate());
			if (txt.equals(""))
				list = qlptr.dsPhieuTra();
			else {
				list = qlptr.timPhieuTra_Nhap(txt);
			}
		}
		
		for (PhieuTra ptra : list) {
			Dia d = qldia.chiTietDia(ptra.getDia().getMaDia());
			TieuDe td = qltd.chiTietTieuDe(d.getTieuDe().getMaTD());
			ChiTietPhieuThue ctpt = ql_ctpt.ChiTietPhieuThue_PT_Dia(ptra.getPt().getMaPT(), d.getMaDia());
			TaiKhoan tk = qltk.chiTietTaiKhoan(ptra.getNhanVien().getTenTK());
			String quaHan, huHong;
			if (ptra.getQuaHan() == 1)
				quaHan = "Có";
			else
				quaHan = "Không";

			if (ptra.getHuHong() == 1)
				huHong = "Có";
			else
				huHong = "Không";

			dm.addRow(new Object[] { ptra.getMaPTr(), d.getMaDia(), td.getTenTD(), ctpt.getHanTra(), ptra.getNgayTra(),
					quaHan, huHong, tk.getHoTen() });
		}
	}
	
	public static void setData(TaiKhoan tk_sql) {
    	if(!(tk_sql == null)) {
			tk = tk_sql;
		}
    }
	private PhieuTra_Gui pt;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLapPhieuThue;
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnTim1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableDia;
	private javax.swing.JTextField txtTim;
	private javax.swing.table.DefaultTableModel dm;

	private JDateChooser dateChooser;

	private PhieuThue_DAO qlpt;
	private PhieuTra_DAO qlptr;
	private Dia_DAO qldia;
	private CT_PhieuThue_DAO ql_ctpt;
	private TieuDe_DAO qltd;
	private TaiKhoan_DAO qltk;
	
	public static TaiKhoan tk;
}
