/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_heThong;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import dao.TaiKhoan_DAO;
import database.Database;
import entities.TaiKhoan;
import gui_main.Main;

import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.awt.Font;

/**
 *
 * @author nmrhu
 */
public class TaiKhoan_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form TaiKhoan_DL
	 */
	public TaiKhoan_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qltk = new TaiKhoan_DAO();

		radKhong = new javax.swing.JRadioButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnLuu = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnXoaTrang = new javax.swing.JButton();
		btnXoaTrang.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtTenTK = new javax.swing.JTextField();
		txtTenTK.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMatKhau = new javax.swing.JTextField();
		txtMatKhau.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtHoTen = new javax.swing.JTextField();
		txtHoTen.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtEmail = new javax.swing.JTextField();
		txtEmail.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSDT = new javax.swing.JTextField();
		txtSDT.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		cbbPhanQuyen = new javax.swing.JComboBox<>();
		cbbPhanQuyen.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 20));
		radCo = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 20));

		txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});

//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		radKhong.setText("Không");
		radKhong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				getRad(radKhong);
			}
		});

		jLabel5.setText("SDT:");

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (quyen == 1)
					ThemTaiKhoan();
				if (quyen == 2)
					CapNhatTaiKhoan();
			}
		});

		jLabel6.setText("Phân quyền:");

		btnXoaTrang.setBackground(new java.awt.Color(255, 0, 0));
		btnXoaTrang.setForeground(new java.awt.Color(255, 255, 255));
		btnXoaTrang.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnXoaTrang.setText("Đóng");

		jLabel7.setText("Truy cập:");

		jLabel1.setText("Tên tài khoản:");

		jLabel2.setText("Mật khẩu:");

		cbbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));

		jLabel3.setText("Họ tên");

		radCo.setSelected(true);
		radCo.setText("Có");
		radCo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				getRad(radCo);
			}
		});

		jLabel4.setText("Email");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtTenTK).addComponent(txtMatKhau).addComponent(txtHoTen)
								.addComponent(txtEmail).addComponent(txtSDT)
								.addComponent(cbbPhanQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addComponent(radCo)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(radKhong))
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 153,
												Short.MAX_VALUE)))
						.addGap(23, 23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(cbbPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel7)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(radCo).addComponent(radKhong)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnLuu)
						.addComponent(btnXoaTrang))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void getRad(JRadioButton rad) {
		radCo.setSelected(false);
		radKhong.setSelected(false);
		rad.setSelected(true);
	}

	public void setData(TaiKhoan tk) {
		txtTenTK.setEditable(false);
		txtTenTK.setText(tk.getTenTK());
		txtMatKhau.setText(tk.getMatKhau());
		txtHoTen.setText(tk.getHoTen());
		txtSDT.setText(tk.getSdt());
		txtEmail.setText(tk.getEmail());
		if (tk.getQuyen() == 0)
			cbbPhanQuyen.setSelectedIndex(1);
		else
			cbbPhanQuyen.setSelectedIndex(0);
		if (tk.getTruyCap() == 1)
			getRad(radCo);
		else {
			getRad(radKhong);
		}

	}
	
	public void clear() {
		txtTenTK.setEditable(true);
		txtTenTK.setText("");
		txtMatKhau.setText("");
		txtHoTen.setText("");
		txtSDT.setText("");
		txtEmail.setText("");
		cbbPhanQuyen.setSelectedIndex(0);
		getRad(radCo);
	}

	public void ThemTaiKhoan() {
		try {
			qltk.themTaiKhoan(getTaiKhoan());
			JOptionPane.showMessageDialog(null, "Thêm thành công");
			main.taiKhoan_pn.DocDuLieuDatabaseVaoTable("");
			clear();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Thêm Không thành công");
		}

	}

	public void CapNhatTaiKhoan() {
		try {
			qltk.capNhatTaiKhoan(getTaiKhoan());
			JOptionPane.showMessageDialog(null, "Cập nhật thành công");
			main.taiKhoan_pn.DocDuLieuDatabaseVaoTable("");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
		}
	}

	public boolean kiemTraNhap() {
		String tenTK = txtTenTK.getText();
		String hoTen = txtHoTen.getText();
		String email = txtEmail.getText();
		String sdt = txtSDT.getText();
		String matKhau = txtMatKhau.getText();

		if (tenTK.equals("") || hoTen.equals("") || matKhau.equals("") || sdt.equals("") || email.equals("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
			return false;
		}
		if (sdt.length() != 10) {
			txtSDT.requestFocus();
			JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại hợp lệ với 10 số");
			return false;
		}
		return true;
	}

	public TaiKhoan getTaiKhoan() {
		String tenTK = txtTenTK.getText();
		String matKhau = txtMatKhau.getText();
		String hoTen = txtHoTen.getText();
		String email = txtEmail.getText();
		String sdt = txtSDT.getText();
		String Squyen = (String) cbbPhanQuyen.getSelectedItem();
		int quyen;
		int truyCap;
		if (Squyen.equals("Nhân viên"))
			quyen = 1;
		else
			quyen = 0;

		if (radCo.isSelected())
			truyCap = 1;
		else
			truyCap = 0;
		TaiKhoan tk = new TaiKhoan(tenTK, matKhau, hoTen, email, sdt, quyen, truyCap);
		return tk;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLuu;
	private javax.swing.JButton btnXoaTrang;
	private javax.swing.JComboBox<String> cbbPhanQuyen;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JRadioButton radCo;
	private javax.swing.JRadioButton radKhong;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JTextField txtHoTen;
	private javax.swing.JTextField txtMatKhau;
	private javax.swing.JTextField txtSDT;
	private javax.swing.JTextField txtTenTK;

	private TaiKhoan_DAO qltk;
	private Main main;
	public static int quyen;
	// End of variables declaration//GEN-END:variables
}
