package gui_baocao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import dao.TieuDe_DAO;
import database.Database;
import entities.TieuDe;

import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.awt.event.ActionEvent;
import java.awt.Font;
import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class BaoCao_Dia_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TaiKhoan
	 */
	public BaoCao_Dia_Gui() {
		setSize(new Dimension(1500, 700));

		initComponents();

		DocDuLieuDatabaseVaoTable("");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();

		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableKhachHang = new javax.swing.JTable();
		btnTim = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 28));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 28));
		jComboBox1 = new JTextField();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new Dimension(1500, 700));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTableKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
		jTableKhachHang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "MaTD", "Tiêu đề", "Số lượng tổng", "Kho", "Cho thuê", "Đã được đặt", "Đặt hàng trước" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false,false };
		});
		jTableKhachHang.getTableHeader().setBackground(new java.awt.Color(89, 159, 255));
		jTableKhachHang.setRowHeight(40);
		jScrollPane1.setViewportView(jTableKhachHang);
		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		btnTim.setBackground(new java.awt.Color(0, 153, 255));
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm kiếm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String txt = jComboBox1.getText().toString();
				DocDuLieuDatabaseVaoTable(txt);
			}
		});

		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("/ Đĩa");

		jLabel1.setForeground(new java.awt.Color(51, 153, 255));
		jLabel1.setText("Báo cáo");
		
		btnInBoCo = new JButton();
		btnInBoCo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				printBaoCao();
			}
		});
		btnInBoCo.setText("In báo cáo");
		btnInBoCo.setForeground(Color.WHITE);
		btnInBoCo.setBackground(new Color(0, 153, 255));
		

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGap(13)
							.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 248, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 915, Short.MAX_VALUE)
							.addComponent(btnInBoCo, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(10)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnInBoCo, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnTim, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
					.addContainerGap())
		);
		this.setLayout(layout);
	}

	public void XoaHetDuLieuTrenTableModel() {
		DefaultTableModel dm = (DefaultTableModel) jTableKhachHang.getModel();
		dm.getDataVector().removeAllElements();
	}

	public void DocDuLieuDatabaseVaoTable(String txt) {
		XoaHetDuLieuTrenTableModel();
		List<TieuDe> list = new ArrayList<TieuDe>();
		qltd = new TieuDe_DAO();
		if (txt.equals(""))
			list = qltd.danhSachTieuDe();
		else
			list = qltd.tim_TieuDe(txt);

		if (list.size() == 0) {
			JOptionPane.showMessageDialog(null, "Không tìm thấy");
			list = qltd.danhSachTieuDe();
		}

		DefaultTableModel dm = (DefaultTableModel) jTableKhachHang.getModel();
		for (TieuDe td : list) {
			int soluong = qltd.soLuongDia(td.getMaTD());
			int kho = qltd.soLuongDia_CoSan(td.getMaTD());
			int choThue = qltd.soLuongDia_ChoThue(td.getMaTD());
			int duocDat = qltd.soLuongDia_DuocDatHang(td.getMaTD());
			int datHang = qltd.soLuongDia_DatHang(td.getMaTD());
			dm.addRow(new Object[] { td.getMaTD(), td.getTenTD(), soluong, kho, choThue, duocDat, datHang });
		}
	}
	
	public void printBaoCao() {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		String date = sdf.format(new Date());
		MessageFormat header = new MessageFormat("Báo cáo Đĩa\n"+"Ngày: " + date );
		try {
			jTableKhachHang.print(JTable.PrintMode.NORMAL, header, null);
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnTim;
	private JTextField jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableKhachHang;

	private TieuDe_DAO qltd;
	private JButton btnInBoCo;
	// End of variables declaration//GEN-END:variables
}
